### ISSUE TITLE
login failure

### ISSUE THREAD

**Issue by kevinburke** [FiloSottile/captive-browser#4]
I'm at SFO airport and trying to connect to their free wifi. I had 8.8.8.8 and 8.8.4.4 in my DNS settings. I joined the network and then started `captive-browser`. When I tried to navigate to a page in the Chrome tab that appeared, I got the following errors in the console:

```
2017/09/28 23:57:45 Redirected DNS lookup: example.com
2017/09/28 23:57:45 [ERR] socks: Failed to handle request: Failed to resolve destination 'example.com': lookup example.com on [::1]:53: dial udp 216.9.98.200:53: connect: network is unreachable
```

(there are more than a few error messages like this)

I don't know enough about how this tool works to be able to debug further, though I'm happy to run any additional commands to help debug the problem.

**Comment by kevinburke** [comment]
here is my config

```toml
# browser is the shell (/bin/sh) command executed once the proxy starts.
# When browser exits, the proxy exits. An extra env var PROXY is available.
#
# Here, we use a separate Chrome instance in Incognito mode, so that
# it can run (and be waited for) alongside the default one, and that
# it maintains no state across runs. To configure this browser open a
# normal window in it, settings will be preserved.
browser = """
    open -n -W -a "Google Chrome" --args \
    --user-data-dir="$HOME/Library/Application Support/Google/Captive" \
    --proxy-server="socks5://$PROXY" \
    --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE localhost" \
    --no-first-run --new-window --incognito \
    http://example.com
"""

# dhcp-dns is the shell (/bin/sh) command executed to obtain the DHCP
# DNS server address. The first match of an IPv4 regex is used.
# IPv4 only, because let's be real, it's a captive portal.
dhcp-dns = "ipconfig getoption en0 domain_name_server"

# socks5-addr is the listen address for the SOCKS5 proxy server.
socks5-addr = "localhost:1666"

# ProTip: to disable the insecure system captive browser see here:
# https://github.com/drduh/macOS-Security-and-Privacy-Guide#captive-portal
# If that doesn't work, disable SIP (remember to re-enable it), and
# rename "/System/Library/CoreServices/Captive Network Assistant.app".
```
